name: psicolbienestar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  http: ^1.2.1
  dio: ^5.4.1
  flutter_riverpod: ^2.5.1
  image_picker: ^1.0.7


  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.1
  video_player: ^2.8.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "images/logo.jpg"
  adaptive_icon_background: "images/logo.jpg"
  min_sdk_android: 21





flutter:
  uses-material-design: true
  assets:
    - assets\lottie\Animation - 1709037189179.json
    - assets\logofinal.png
    - images/
   